### PR TITLE
CV Enabled for 3 qubits and Added Gates

### PR DESCRIPTION
**Pull request by lockwo**
Added CVDagger Gate and Support for CVDagger and CV for 3 qubit systems. Added CVDagger gate to docs.

### CODE REVIEW

**Comment by harshangrjn** [comment]
Thanks @lockwo ! Can you also add a few tests to this [file](https://github.com/harshangrjn/QuantumCircuitOpt.jl/blob/master/test/gates_tests.jl) for these new gates to bring the coverage back up to ~92-93%? You can test the products against the QCO.ToffoliGate()?

**Comment by lockwo** [comment]
I added a toffoli test and an identity check, what other test types should be added?

**Comment by harshangrjn** [comment]
@lockwo In [here](https://github.com/harshangrjn/QuantumCircuitOpt.jl/pull/12/files), you can see a few gates (like CV_12 and others) are not covered by tests (codecov results). Could you add a few more tests, like verifying these new gates as a decomposition using H, T and CNOT gates?

**Comment by lockwo** [comment]
Alright, fixed everything up so all the tests pass

**Pull request merged**
